sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t calebadegbite/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true calebadegbite/docker-react npm run test
